if(Battle_GetMenuChoiceButton()=BATTLE_BUTTON.ACT||Battle_GetMenuChoiceButton()=BATTLE_BUTTON.ITEM||Battle_GetMenuChoiceButton()=BATTLE_BUTTON.MERCY){
	if(Battle_GetMenuChoiceButton()=BATTLE_BUTTON.MERCY&&Battle_GetTurnNumber()=17){
	instance_create_depth(0,0,0,battle_snowsans_spared)
	}else{
		Battle_SetNextState(BATTLE_MENU.BUTTON)
		Battle_GotoNextState()
}}
if(Battle_GetMenuChoiceButton()=BATTLE_BUTTON.FIGHT){
		titr_head.image_index=0
		titr_body.image_index=0
	instance_create_depth(0,0,0,asset_get_index("battle_snowsans_turn"+string(Battle_GetTurnNumber())))
}