/*ab=instance_create_depth(0,0,0,battle_bg)
ab.image_blend=$E16941
ab.image_yscale=6
ab.alarm[1]=1
ab.tempscale=6
ba=instance_create_depth(0,room_height,0,battle_bg)
ba.image_blend=c_orange
ba.image_yscale=-6
ba.alarm[1]=1
ba.tempscale=-6*/
depth=DEPTH_UI.TEXT
instance_create_depth(0,0,depth+2,obj_background)
if!(os_type=os_android||os_type=os_ios||os_type=os_winphone||os_browser=browser_ie_mobile||os_browser=browser_ie_mobile){
instance_create_depth(0,0,depth+1,obj_effect_space)}

//rainbow=0
choice=0
choice_min=-1
choice_max=8
phase=0
phases=0
temp=0
quit=0
_shop=0
enabled=true
warning_color=c_white
warning_countdown=-1
