if(current_month>=3&&current_month<=5&&!audio_is_playing(bgm_menu_spring_autumn)){
BGM_Play(0,bgm_menu_spring_autumn,true,1,1)}
if(current_month>=6&&current_month<=8&&!audio_is_playing(bgm_menu_summer)){
BGM_Play(0,bgm_menu_summer,true,1,1)}
if(current_month>=9&&current_month<=11&&!audio_is_playing(bgm_menu_spring_autumn)){
BGM_Play(0,bgm_menu_spring_autumn,true,1,1)}
if((current_month=12||current_month<=2)&&!audio_is_playing(bgm_menu_winter)){
BGM_Play(0,bgm_menu_winter,true,1,1)}

/*ab=instance_create_depth(0,0,0,battle_bg)
ab.image_blend=$E16941
ab.image_yscale=6
ab.alarm[1]=1
ab.tempscale=6
ba=instance_create_depth(0,room_height,0,battle_bg)
ba.image_blend=c_orange
ba.image_yscale=-6
ba.alarm[1]=1
ba.tempscale=-6*/
depth=DEPTH_UI.TEXT
instance_create_depth(0,0,0,obj_effect_space)

rainbow=0
choice=0
choice_max=0
phase=0
phases=0
temp=0
quit=0
_shop=0
enabled=true
warning_color=c_white
warning_countdown=-1
