Battle_SetTurnInfo(BATTLE_TURN.TIME,770)
Battle_SetTurnInfo(BATTLE_TURN.BOARD_UP,64)
Battle_SetTurnInfo(BATTLE_TURN.BOARD_DOWN,64)
Battle_SetTurnInfo(BATTLE_TURN.BOARD_LEFT,64)
Battle_SetTurnInfo(BATTLE_TURN.BOARD_RIGHT,64)
depth=battle_enemy_warma.depth+1
_x=320//battle_enemy_warma.x//640+64
_y=battle_enemy_warma.y
temp=false