if(keyboard_check_direct(vk_shift)){
if(keyboard_check_pressed(ord("A"))){_naming_name+="A"}
if(keyboard_check_pressed(ord("B"))){_naming_name+="B"}
if(keyboard_check_pressed(ord("C"))){_naming_name+="C"}
if(keyboard_check_pressed(ord("D"))){_naming_name+="D"}
if(keyboard_check_pressed(ord("E"))){_naming_name+="E"}
if(keyboard_check_pressed(ord("F"))){_naming_name+="F"}
if(keyboard_check_pressed(ord("G"))){_naming_name+="G"}
if(keyboard_check_pressed(ord("H"))){_naming_name+="H"}
if(keyboard_check_pressed(ord("I"))){_naming_name+="I"}
if(keyboard_check_pressed(ord("J"))){_naming_name+="J"}
if(keyboard_check_pressed(ord("K"))){_naming_name+="K"}
if(keyboard_check_pressed(ord("L"))){_naming_name+="L"}
if(keyboard_check_pressed(ord("M"))){_naming_name+="M"}
if(keyboard_check_pressed(ord("N"))){_naming_name+="N"}
if(keyboard_check_pressed(ord("O"))){_naming_name+="O"}
if(keyboard_check_pressed(ord("P"))){_naming_name+="P"}
if(keyboard_check_pressed(ord("Q"))){_naming_name+="Q"}
if(keyboard_check_pressed(ord("R"))){_naming_name+="R"}
if(keyboard_check_pressed(ord("S"))){_naming_name+="S"}
if(keyboard_check_pressed(ord("T"))){_naming_name+="T"}
if(keyboard_check_pressed(ord("U"))){_naming_name+="U"}
if(keyboard_check_pressed(ord("V"))){_naming_name+="V"}
if(keyboard_check_pressed(ord("W"))){_naming_name+="W"}
if(keyboard_check_pressed(ord("X"))){_naming_name+="X"}
if(keyboard_check_pressed(ord("Y"))){_naming_name+="Y"}
if(keyboard_check_pressed(ord("Z"))){_naming_name+="Z"}
}