if(Input_IsPressed(INPUT.CONFIRM)){
	audio_stop_sound(bgm)
	instance_destroy(battle_button_fight)
	Battle_EndTurn()
}
if(Battle_GetTurnTime()=240){
image_speed=10}
if(Battle_GetTurnTime()=240-(60/10)*12){
image_speed=0}
if(Battle_GetTurnTime()=240-(60/10)*8){
audio_play_sound(snd_asgore_spear,0,0)}
if(Battle_GetTurnTime()=120){
fader.color=c_black
Fader_Fade(0,1,60)}
if(Battle_GetTurnTime()=50){
audio_play_sound(snd_gb_release,0,0)
instance_destroy(battle_button_fight)}