if(Battle_GetTurnTime()=40){
fader.color=c_white
Anim_Create(fader,"alpha",0,0,0,1,15)
alarm[0]=40}
if(Battle_GetTurnTime()=855){
titr_head.image_index=4
Camera_Shake(10,10)
instance_create_depth(0,0,0,blur_shader)}
if(Battle_GetTurnTime()=420){
Battle_SetSoul(battle_soul_blue)}
if(Battle_GetTurnTime()=360){
alarm[1]=1}
