if(_dir==DIR.RIGHT){
	_aim_x=x-battle_board.left+sprite_get_width(spr_battle_menu_fight_aim)-5;
	//Anim_Create(id,"_aim_x",0,0,_aim_x,battle_board.left+battle_board.right+sprite_get_width(spr_battle_menu_fight_aim),70);
}else{
	//_aim_x=x+battle_board.right+sprite_get_width(spr_battle_menu_fight_aim)/2;
	_aim_x_1=x+battle_board.right-sprite_get_width(spr_battle_menu_fight_aim)+5;
	//Anim_Create(id,"_aim_x_1",0,0,_aim_x_1,-(battle_board.left+battle_board.right+sprite_get_width(spr_battle_menu_fight_aim)),70);
}
_input_acceptable=true;
alarm[6]=10