Anim_Uninit();
Dialog_Uninit();
Flag_Uninit();
Encounter_Uninit();
Input_Uninit();
Demo_Uninit();
Shop_Uninit();
file_delete(working_directory+"console.txt");
if(file_exists(working_directory+GAME_SAVE_NAME+"/file10.ini")){file_delete(working_directory+GAME_SAVE_NAME+"/file10.ini")}
if(directory_exists(working_directory+GAME_SAVE_NAME+"/flag/10")){directory_destroy(working_directory+GAME_SAVE_NAME+"/flag/10")}