var a=Battle_MakeLineBomb(battle_soul.x-128,battle_soul.y-128,45)
a.sprite_index=spr_rabbit_bomb
var a=Battle_MakeLineBomb(battle_soul.x+128,battle_soul.y+128,45)
a.sprite_index=spr_rabbit_bomb
var a=Battle_MakeLineBomb(battle_soul.x+128,battle_soul.y-128,45)
a.sprite_index=spr_rabbit_bomb
var a=Battle_MakeLineBomb(battle_soul.x-128,battle_soul.y+128,45)
a.sprite_index=spr_rabbit_bomb
alarm[1]=90