if(Battle_GetTurnNumber()>=11){
if(Battle_GetMenuChoiceButton()=BATTLE_BUTTON.FIGHT){
instance_create_depth(0,0,0,battle_utcsans_turn_hit)
}
if(Battle_GetMenuChoiceButton()=BATTLE_BUTTON.MERCY){
instance_create_depth(0,0,0,battle_utcsans_turn_spared)
}
}else{
if(Battle_GetMenuChoiceButton()=BATTLE_BUTTON.ACT||Battle_GetMenuChoiceButton()=BATTLE_BUTTON.MERCY){
		Battle_SetNextState(BATTLE_MENU.BUTTON)
		Battle_GotoNextState()
}
if(Battle_GetMenuChoiceButton()=BATTLE_BUTTON.FIGHT||Battle_GetMenuChoiceButton()=BATTLE_BUTTON.ITEM){
	_face=0
	instance_create_depth(0,0,0,asset_get_index("battle_utcsans_turn"+string(Battle_GetTurnNumber())))
}
}