if(Battle_GetTurnNumber()>=11){
if(Battle_GetMenuChoiceButton()=0){
instance_create_depth(0,0,0,battle_utcsans_turn_hit)
}
if(Battle_GetMenuChoiceButton()=3){
instance_create_depth(0,0,0,battle_utcsans_turn_spared)
}
}else{
if(Battle_GetMenuChoiceButton()=1||Battle_GetMenuChoiceButton()=3){
		Battle_SetNextState(BATTLE_MENU.BUTTON)
		Battle_GotoNextState()
}
if(Battle_GetMenuChoiceButton()=0||Battle_GetMenuChoiceButton()=2){
	_face=0
	instance_create_depth(0,0,0,asset_get_index("battle_utcsans_turn"+string(Battle_GetTurnNumber())))
}
}