var angle=random_range(45,135)
angle-=random_range(35,55)
var _x=battle_soul.x+lengthdir_x(320,angle)
var _y=battle_soul.y+lengthdir_y(320,angle)
var _xtarget=battle_soul.x+lengthdir_x(180,angle)
var _ytarget=battle_soul.y+lengthdir_y(180,angle)
Battle_MakeFriendlyPellet(_x,_y,_xtarget,_ytarget,0,20,20,10,angle+180,angle+90,1,true,battle_bullet_friendlypellet,spr_battle_bone)
var angle=random_range(45,135)
angle+=random_range(35,55)
var _x=battle_soul.x+lengthdir_x(320,angle)
var _y=battle_soul.y+lengthdir_y(320,angle)
var _xtarget=battle_soul.x+lengthdir_x(180,angle)
var _ytarget=battle_soul.y+lengthdir_y(180,angle)
Battle_MakeFriendlyPellet(_x,_y,_xtarget,_ytarget,0,20,20,10,angle+180,angle+90,1,true,battle_bullet_friendlypellet,spr_battle_bone)
alarm[3]=120