event_inherited();

//移动
if(Battle_GetState()==BATTLE_STATE.IN_TURN && moveable){
	var SPD=Player_GetSpdTotal()
	var SPD=(Input_IsHeld(INPUT.CANCEL) ? SPD/2 : SPD);
	repeat(SPD*10){
		if(Input_IsHeld(INPUT.DOWN)){
			movedown=0
			moveup=1
			moveleft=0
			moveright=0
		}
		if(Input_IsHeld(INPUT.UP)){
			movedown=1
			moveup=0
			moveleft=0
			moveright=0
		}
		if(Input_IsHeld(INPUT.RIGHT)){
			movedown=0
			moveup=0
			moveleft=1
			moveright=0
			}
		if(Input_IsHeld(INPUT.LEFT)){
			movedown=0
			moveup=0
			moveleft=0
			moveright=1
			}
		if(movedown=1){
			if(!position_meeting(x,(y-sprite_height/2)+0.05,block)){
				y+=0.15;
			moveup=0
			moveleft=0
			moveright=0
			}
		}
		if(moveup=1){
			if(!position_meeting(x,(y-sprite_height/2)-0.05,block)){
				y-=0.15;
			movedown=0
			moveleft=0
			moveright=0
			}
		}
		if(moveright=1){
			if(!position_meeting((x-sprite_width/2)+0.05,y,block)){
				x+=0.15;
			movedown=0
			moveup=0
			moveleft=0
			}
		}
		if(moveleft=1){
			if(!position_meeting((x-sprite_width/2)-0.05,y,block)){
				x-=0.15;
			movedown=0
			moveup=0
			moveright=0
			}
		}
	}
}

if(Battle_GetState()=BATTLE_STATE.IN_TURN){
if(keyboard_check(ord("D"))){
image_angle+=6}
if(keyboard_check(ord("A"))){
image_angle-=6}
}

if(display_mouse_get_x()=window_get_x()+window_mouse_get_x()&&display_mouse_get_y()=window_get_y()+window_mouse_get_y()&&Battle_GetState()=BATTLE_STATE.IN_TURN){
image_angle=point_direction(x,y,mouse_x,mouse_y)-90
}

if(Input_IsPressed(INPUT.CONFIRM)&&Battle_GetState()=BATTLE_STATE.IN_TURN){
obj=instance_create_depth(x,y,DEPTH_BATTLE.SOUL+1,battle_soul_yellow_bullet)
obj.image_angle=image_angle
//Anim_Create(obj,"x",0,0,obj.x,lengthdir_x(1000,image_angle+90)-obj.x,20)
//Anim_Create(obj,"y",0,0,obj.y,lengthdir_y(1000,image_angle+90)-obj.y,20)
}