with(menuspatula){instance_destroy()}
if(Battle_GetMenuChoiceButton()=BATTLE_BUTTON.ACT||Battle_GetMenuChoiceButton()=BATTLE_BUTTON.ITEM||Battle_GetMenuChoiceButton()=BATTLE_BUTTON.MERCY){
	if(Battle_GetMenuChoiceButton()=BATTLE_BUTTON.MERCY&&Battle_GetTurnNumber()=11){
		instance_create_depth(0,0,0,battle_sponge_spared)}else{
		Battle_SetNextState(BATTLE_MENU.BUTTON)
		Battle_GotoNextState()
}}
if(Battle_GetMenuChoiceButton()=BATTLE_BUTTON.FIGHT){
	_face=0
	instance_create_depth(0,0,0,asset_get_index("battle_sponge_p2_turn"+string(Battle_GetTurnNumber())))
}