if(Battle_GetTurnTime()=80){
alarm[0]=-1
Battle_SetSoul(battle_soul_red)
audio_play_sound(snd_ding,0,0)
instance_destroy(a)
if(instance_exists(battle_bullet_gb_new)){
with(battle_bullet_gb_new){
instance_destroy()
if(instance_exists(a)){
instance_destroy(a)}
if(instance_exists(b)){
instance_destroy(b)}
}}
Battle_MakeBoneWallBottom(25,55,55)
Battle_MakeBoneWallTop(25,55,55)
Battle_MakeBoneWallLeft(25,55,55)
Battle_MakeBoneWallRight(25,55,55)
}